[package]
name = "salbp-1"
version = "0.2.0"
edition = "2024"

[dependencies]
fixedbitset = "0.5"
clap = { version = "4.5", features = ["derive"] }
tikv-jemallocator = "0.6"
rpid = "0.2"
dypdl = "0.10"
dypdl-heuristic-search = "0.10"
io-util = { version = "0.2", path = "../io-util" }
